version: 2.1
workflows:
  ci-cd:
    jobs:
      - publish:
          context: org-global
jobs:
  publish:
    working_directory: ~/app
    docker:
      - image: node:14
    steps:
      - checkout
      - run: npm i
      - run: npm t
      - run: npm run lint
      - run:
          name: Set npmrc credentials
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Publish to NPM
          command: npm_config_yes=true npx published --git-tag
